"""initial schema

Revision ID: 0a87f53b66fe
Revises:
Create Date: 2026-03-30 08:30:34.012996
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0a87f53b66fe"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_graph_edges",
        sa.Column("source_key", sa.String(length=512), nullable=False),
        sa.Column("target_key", sa.String(length=512), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "cites",
                "cited_by",
                "similar_to",
                "authored_by",
                "co_authored",
                "version_of",
                name="relation_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("provider_source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("source_key", "target_key", "relation_type"),
    )
    op.create_index("ix_graph_relation", "paper_graph_edges", ["relation_type"], unique=False)
    op.create_index("ix_graph_source", "paper_graph_edges", ["source_key"], unique=False)
    op.create_index("ix_graph_target", "paper_graph_edges", ["target_key"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "collections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("private", "shared", "public", name="visibility_enum"),
            server_default="private",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("paper", "collection", "author", name="note_target_enum"),
            nullable=False,
        ),
        sa.Column("target_key", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notes_user_target", "notes", ["user_id", "target_type", "target_key"], unique=False
    )
    op.create_table(
        "user_paper_tags",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("paper_canonical_key", sa.String(length=512), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "paper_canonical_key", "tag"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    op.create_table(
        "collection_members",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("owner", "editor", "viewer", name="role_enum"), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("collection_id", "user_id"),
    )
    op.create_table(
        "collection_papers",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("paper_canonical_key", sa.String(length=512), nullable=False),
        sa.Column("added_by", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("added_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["added_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("collection_id", "paper_canonical_key"),
    )
    op.create_table(
        "user_paper_states",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("paper_canonical_key", sa.String(length=512), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "unseen",
                "seen",
                "saved",
                "to_read",
                "reading",
                "read",
                "important",
                "ignored",
                "excluded",
                name="reading_state_enum",
            ),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "paper_canonical_key", "collection_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_paper_states")
    op.drop_table("collection_papers")
    op.drop_table("collection_members")
    op.drop_table("user_preferences")
    op.drop_table("user_paper_tags")
    op.drop_index("ix_notes_user_target", table_name="notes")
    op.drop_table("notes")
    op.drop_table("collections")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_graph_target", table_name="paper_graph_edges")
    op.drop_index("ix_graph_source", table_name="paper_graph_edges")
    op.drop_index("ix_graph_relation", table_name="paper_graph_edges")
    op.drop_table("paper_graph_edges")
    # ### end Alembic commands ###
